accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from accounts.views import signup

urlpatterns = [
   path("login/", auth_views.LoginView.as_view(), name="login"),
   path("logout/", auth_views.LogoutView.as_view(), name="logout"),
   path("signup/", signup, name="signup"),
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("home"))),
    path("receipts/", include("receipts.urls")),
    path("accounts/", include("accounts.urls")),
]

receipts/urls.py
from django.urls import path
from receipts.views import (
    ReceiptListView,
    ReceiptCreateView,
    AccountCreateView,
    AccountListView,
    CategoryCreateView,
    CategoryListView,
)

urlpatterns = [
    path("", ReceiptListView.as_view(), name="home"),
    path("create/", ReceiptCreateView.as_view(), name="receipt_create"),
    path("accounts/", AccountListView.as_view(), name="accounts_list"),
    path("accounts/create/", AccountCreateView.as_view(), name="account_create"),
    path("categories/", CategoryListView.as_view(), name="categories_list"),
    path("categories/create/", CategoryCreateView.as_view(), name="category_create"),
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL

# Create your models here.
class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(max_digits=10, decimal_places=3)
    tax = models.DecimalField(max_digits=10, decimal_places=3)
    date = models.DateField()
    category = models.ForeignKey("ExpenseCategory", on_delete=models.CASCADE, related_name="receipts")
    account = models.ForeignKey("Account", on_delete=models.CASCADE, related_name="receipts", null=True)
    purchaser = models.ForeignKey(USER_MODEL, on_delete=models.CASCADE, related_name="receipts")

class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(USER_MODEL, on_delete=models.CASCADE, related_name="categories")

    def __str__(self):
        return self.name

class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    author = models.ForeignKey(USER_MODEL, on_delete=models.CASCADE, related_name="accounts")

    def __str__(self):
        return self.name

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login



# Create your views here.
def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid:
            username = request.POST["username"]
            password = request.POST["password1"]
            user = User.objects.create_user(username, "user@user.com", password)
            user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm(request.POST)
    context = {"form": form}
    return render(request, "registration/signup.html", context)

receipts/views.py
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin

from receipts.models import Account, ExpenseCategory, Receipt

# Create your views here.


class ReceiptListView(LoginRequiredMixin, ListView):
    model = Receipt
    template_name = "receipts/list.html"

    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)

    def get_context_data(self, **kwargs):
    # Let the parent class get the context for
    # the actual Post for its detail
        context = super().get_context_data(**kwargs)

    # Print it out to see what's in it
        from pprint import pprint
        pprint(context)

    # Return it like nothing ever happened
        return context


class ReceiptCreateView(LoginRequiredMixin, CreateView):
    model = Receipt
    fields = ["vendor", "total", "tax", "date", "category", "account"]
    template_name = "receipts/create.html"

    def form_valid(self, form):
        item = form.save(commit=False)
        item.purchaser = self.request.user
        item.save()
        return redirect("home")


class AccountCreateView(LoginRequiredMixin, CreateView):
    model = Account
    fields = ["name", "number"]
    template_name = "accounts/create.html"

    def form_valid(self, form):
        item = form.save(commit=False)
        item.author = self.request.user
        item.save()
        return redirect("home")


class AccountListView(LoginRequiredMixin, ListView):
    model = Account
    template_name = "accounts/list.html"

    def get_queryset(self):
        return Account.objects.filter(author=self.request.user)

    def get_context_data(self, **kwargs):
    # Let the parent class get the context for
    # the actual Post for its detail
        context = super().get_context_data(**kwargs)

    # Print it out to see what's in it
        from pprint import pprint
        pprint(context)

    # Return it like nothing ever happened
        return context


class CategoryCreateView(LoginRequiredMixin, CreateView):
    model = ExpenseCategory
    fields = ["name"]
    template_name = "categories/create.html"

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("home")


class CategoryListView(LoginRequiredMixin, ListView):
    model = ExpenseCategory
    template_name = "categories/list.html"

    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)

receipts/templates/accounts/create.html
{% extends 'base.html' %}

{% block content %}
<main>
    <h1>Create Account</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div>
      <button class="button">Create</button>
    </div>
  </form>
</main>
{% endblock content %}

receipts/templates/accounts/list.html
{% extends 'base.html' %}

{% block content %}
<main>
    <h1>Accounts</h1>
    <table class="center">
        <thead>
            <tr>
                <th>Name</th>
                <th>Number</th>
                <th>Number of Receipts</th>
            </tr>
        </thead>
        <tbody>
            {% for account in account_list %}
            <tr>
                <td>{{ account.name }}</td>
                <td>{{ account.number }}</td>
                <td>{{ account.receipts.all|length }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</main>
{% endblock content %}

receipts/templates/base.html
{% load static %}

<!doctype html>
<html>
    <head>
        <title>Me Receipts</title>
        <link rel="stylesheet" href="{% static '/app.css' %}">
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    <li><a href="{% url "home" %}">Receipts</a></li>
                    <li><a href="{% url "receipt_create" %}">Create receipt</a></li>
                    <li><a href="{% url "accounts_list" %}">Accounts</a></li>
                    <li><a href="{% url "account_create" %}">Create Account</a></li>
                    <li><a href="{% url "categories_list" %}">Categories</a></li>
                    <li><a href="{% url "category_create" %}">Create Category</a></li>
                    <li><a href="{% url "logout" %}">Logout</a></li>
                </ul>
            </nav>
        </header>
        {% block content %}
        {% endblock content %}
        <footer></footer>
    </body>
</html>

receipts/templates/categories/create.html
{% extends 'base.html' %}

{% block content %}
<main class="recipe-form">
    <h1>Create Category</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="control">
      <button class="button">Create</button>
    </div>
  </form>
</main>
{% endblock content %}

receipts/templates/categories/list.html
{% extends 'base.html' %}

{% block content %}
<main>
    <h1>Expense Categories</h1>
    <table class="center">
        <thead>
            <tr>
                <th>Name</th>
                <th>Number of receipts</th>
            </tr>
        </thead>
        <tbody>
            {% for category in expensecategory_list %}
            <tr>
                <td>{{ category.name }}</td>
                <td>{{ category.receipts.all|length }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</main>
{% endblock content %}

receipts/templates/receipts/create.html
{% extends 'base.html' %}

{% block content %}
<main class="recipe-form">
    <h1>Create Receipts</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="control">
      <button class="button">Create</button>
    </div>
  </form>
</main>
{% endblock content %}

receipts/templates/receipts/list.html
{% extends 'base.html' %}

{% block content %}
<main>
    <h1>Receipts</h1>
    <table class="center">
        <thead>
            <tr>
                <th>Vendor</th>
                <th>Total</th>
                <th>Tax</th>
                <th>Date</th>
                <th>Category</th>
                <th>Account</th>
            </tr>
        </thead>
        <tbody>
            {% for receipt in receipt_list %}
            <tr>
                <td>{{ receipt.vendor }}</td>
                <td>{{ receipt.total }}</td>
                <td>{{ receipt.tax }}</td>
                <td>{{ receipt.date }}</td>
                <td>{{ receipt.category }}</td>
                <td>{{ receipt.account }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</main>
{% endblock content %}